"Online Appointment Booking"
"Patient Follow-Up Messages"
"WhatsApp & SMS Reminders"
"Clinic Staff Accounts (3)"
"Social Media Automation"
"ePrescription (Digital Prescription)"
"Track Patients & Growth Metrics"
"Access to Doctor's App"
"Teleconsultation (100/month)"
"Basic Mail & Chat Support"