"use client";

import React, { useState } from "react";
import SelectDropdown from "./SelectDropdown"

const GeneralSettings: React.FC = () => {
  const [enableAnalytics, setEnableAnalytics] = useState(false);
  const [enablePostingLogs, setEnablePostingLogs] = useState(false);
  const [enableTimestampLink, setEnableTimestampLink] = useState(false);
  const [selectedTimezone, setSelectedTimezone] = useState("Asia/Dili");

  const timezones: string[] = [
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
  ];

  return (
    <div className="p-6 space-y-6">
      <SelectDropdown
        label="Timezone"
        selectedValue={selectedTimezone}
        setSelectedValue={setSelectedTimezone}
        options={timezones}
      />

      <ToggleSwitch
        label="Enable Google Analytics Campaign Tracking"
        description="Enable campaign tracking if you want to see how much traffic is generated by Social Auto Poster."
        enabled={enableAnalytics}
        onToggle={() => setEnableAnalytics(!enableAnalytics)}
      />

      <ToggleSwitch
        label="Enable Social Posting Logs"
        description="Enable this to store your social posting activities into the database which can be viewed from 'Logs' section."
        enabled={enablePostingLogs}
        onToggle={() => setEnablePostingLogs(!enablePostingLogs)}
      />

      <ToggleSwitch
        label="Enable Timestamp Link"
        description="Enable this to send timestamp with Social Link post."
        enabled={enableTimestampLink}
        onToggle={() => setEnableTimestampLink(!enableTimestampLink)}
      />

      <button className="mt-6 px-5 py-2.5 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 cursor-pointer">
        Save
      </button>
    </div>
  );
};

interface ToggleSwitchProps {
  label: string;
  description: string;
  enabled: boolean;
  onToggle: () => void;
}

const ToggleSwitch: React.FC<ToggleSwitchProps> = ({
  label,
  description,
  enabled,
  onToggle,
}) => (
  <div>
    <div className="flex items-center justify-between">
      <span className="text-sm font-medium text-gray-900">{label}</span>
      <button
        onClick={onToggle}
        className={`relative inline-flex h-7 w-12 items-center rounded-full transition-colors ${
          enabled ? "bg-blue-600" : "bg-gray-400"
        } cursor-pointer`}
      >
        <span
          className={`inline-block h-6 w-6 transform rounded-full bg-white shadow transition-transform ${
            enabled ? "translate-x-5" : "translate-x-1"
          }`}
        />
      </button>
    </div>
    <p className="text-sm text-gray-500">{description}</p>
  </div>
);

export default GeneralSettings;
