// GeneralSettings.tsx
import React from "react";

const GeneralSettings: React.FC = () => {
  return (
    <div style={{ padding: "20px" }}>
      <div>
        <label htmlFor="timezone">Timezone</label>
        <select
          id="timezone"
          style={{
            width: "100%",
            padding: "8px",
            marginTop: "5px",
            borderRadius: "4px",
            border: "1px solid #ccc",
          }}
        >
          <option value="Asia/Dili">Asia/Dili</option>
        </select>
      </div>
      <div style={{ marginTop: "20px" }}>
        <label>
          <input type="checkbox" />
          Enable Google Analytics Campaign Tracking
        </label>
        <p style={{ fontSize: "12px", color: "#666" }}>
          Enable campaign tracking if you want to see how much traffic is
          generated by Social Auto Poster.
        </p>
      </div>
      <div style={{ marginTop: "20px" }}>
        <label>
          <input type="checkbox" />
          Enable Social Posting Logs
        </label>
        <p style={{ fontSize: "12px", color: "#666" }}>
          Enable this to store your social posting activities into the
          database which can be viewed from "Logs" section.
        </p>
      </div>
      <div style={{ marginTop: "20px" }}>
        <label>
          <input type="checkbox" />
          Enable Timestamp Link
        </label>
        <p style={{ fontSize: "12px", color: "#666" }}>
          Enable this to send timestamp with Social Link post.
        </p>
      </div>
      <button
        style={{
          marginTop: "20px",
          padding: "10px 15px",
          background: "blue",
          color: "white",
          border: "none",
          borderRadius: "4px",
          cursor: "pointer",
        }}
      >
        Save
      </button>
    </div>
  );
};

export default GeneralSettings;