// GeneralSettings.tsx
import React from "react";

const GeneralSettings: React.FC = () => {
  return (
    <div className="p-6 space-y-6"> {/* Increased padding and added space-y-6 */}
      <div>
        <label htmlFor="timezone" className="block text-sm font-medium text-gray-700 mb-1"> {/* Added mb-1 */}
          Timezone
        </label>
        <select
          id="timezone"
          className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
        >
          <option value="Asia/Dili">Asia/Dili</option>
        </select>
      </div>
      <div>
        <label className="flex items-center cursor-pointer">
          <input type="checkbox" className="sr-only peer" />
          <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
          <span className="ml-3 text-sm font-medium text-gray-900">
            Enable Google Analytics Campaign Tracking
          </span>
        </label>
        <p className="text-sm text-gray-500 mt-1"> {/* increased text size slightly */}
          Enable campaign tracking if you want to see how much traffic is
          generated by Social Auto Poster.
        </p>
      </div>
      <div>
        <label className="flex items-center cursor-pointer">
          <input type="checkbox" className="sr-only peer" />
          <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
          <span className="ml-3 text-sm font-medium text-gray-900">
            Enable Social Posting Logs
          </span>
        </label>
        <p className="text-sm text-gray-500 mt-1">
          Enable this to store your social posting activities into the
          database which can be viewed from "Logs" section.
        </p>
      </div>
      <div>
        <label className="flex items-center cursor-pointer">
          <input type="checkbox" className="sr-only peer" />
          <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
          <span className="ml-3 text-sm font-medium text-gray-900">
            Enable Timestamp Link
          </span>
        </label>
        <p className="text-sm text-gray-500 mt-1">
          Enable this to send timestamp with Social Link post.
        </p>
      </div>
      <button
        className="mt-6 px-5 py-2.5 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
      >
        Save
      </button>
    </div>
  );
};

export default GeneralSettings;