name: Build & Deploy Node.js App to VPS
on:
  push:
    branches: [ "main" ]          # deploy only when main is updated
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production            # triggers GitHub's built-in manual approval
    # 1️⃣ ──────────────────────────────────────────────────────────────────────
    # Add every secret you need for build/run below.
    # These are **masked** in the logs by GitHub.
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}   # example public var
    # 2️⃣ ──────────────────────────────────────────────────────────────────────
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port:     ${{ secrets.VPS_PORT }}
          key:      ${{ secrets.VPS_SSH_KEY }}
          # Forward the secret names to the remote shell (comma-separated list)
          envs: DATABASE_URL
          script: |
            # ── Load Node.js 22 via nvm (non-interactive shell) ───────────
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm use 22
            
            # ── Go to the app directory ────────────────────────────────────
            echo "=== NAVIGATING TO APP DIRECTORY ==="
            cd /home/LiveDoctors-app/LD2025
            echo "Current directory: $(pwd)"
            
            # ── List directory contents ────────────────────────────────────
            echo "=== DIRECTORY CONTENTS ==="
            ls -la
            
            # ── Check for important files ──────────────────────────────────
            echo "=== CHECKING FOR KEY FILES ==="
            echo "package.json exists: $([ -f package.json ] && echo 'YES' || echo 'NO')"
            echo "src/ directory exists: $([ -d src ] && echo 'YES' || echo 'NO')"
            echo "db/ directory exists: $([ -d db ] && echo 'YES' || echo 'NO')"
            echo "next.config.js exists: $([ -f next.config.js ] && echo 'YES' || echo 'NO')"
            echo "tsconfig.json exists: $([ -f tsconfig.json ] && echo 'YES' || echo 'NO')"
            
            # ── Check git status ───────────────────────────────────────────
            echo "=== GIT STATUS ==="
            git status --porcelain
            echo "Current branch: $(git branch --show-current)"
            echo "Latest commit: $(git log -1 --oneline)"
