name: Build & Deploy Node.js App to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Used for build on GitHub runner, adjust if your build needs Node 22

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22
            cd /home/LiveDoctors-app/LD2025
            export $(grep -v '^#' .env | xargs)
            npm install
            npm run build
            pm2 restart livedoctors || pm2 start npm --name "livedoctors" -- start
