name: Build & Deploy Node.js App to VPS
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # Add any other environment variables your app needs during build
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          # Add other secrets as needed
  deploy:
    name: Deploy to VPS
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use --lts
            cd /home/LiveDoctors-app/LD2025
            set -a
            source .env
            set +a
            echo "DATABASE_URL is: $DATABASE_URL"
            npm install
            npm run build
            pm2 start npm --name "livedoctors" -- run start:prod --update-env
